<?php

/**
 * @file
 * Project Source: GitHub module hooks and functions.
 */


/**
 * Includes private/helpers file. Functions contained here should not be used
 * by any other module.
 */
require_once(dirname(__FILE__) . '/includes/project_src_github.private.inc');


/**
 * Implements hook_menu().
 */
function project_src_github_menu() {
  // Admin callback.
  $items['admin/config/development/github-src'] = array(
    'title' => 'Project Source: GitHub',
    'description' => 'Configure GitHub API options for the Project Source module.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('project_src_github_settings'),
    'access arguments' => array('administer project github src'),
    'file' => 'includes/project_src_github.admin.inc',
  );

  // Callback to download archive packages in the correct format.
  $items['drupal/github-release-files/%/%/%/download.tar.gz'] = array(
    'title' => 'File download callback for a specific project release',
    'delivery callback' => 'project_src_deliver_clean_page',
    'page callback' => 'project_src_github_get_archive',
    'page arguments' => array(2, 3, 4),
    'access callback' => TRUE,
    'file' => 'includes/project_src_github.archive.inc',
    'type' => MENU_CALLBACK,
  );

  return $items;
}


/**
 * Implements hook_permission().
 */
function project_src_github_permission() {
  return array(
    'administer project github src' => array(
      'title' => t('Administer Project Source: GitHub'),
      'description' => t('Perform administration tasks for Project Source: GitHub'),
      'restrict access' => TRUE,
    ),
  );
}


/**
 * Implements hook github_webhook_event().
 *
 * Clears Project Source: GitHub caches on commit to a tracked repository.
 */
function project_src_github_github_webhook_event($payload, &$response, $args) {
  // @todo Filter down to a subset before clearing the cache.
  project_src_github_clear_cache();
}


/**
 * Clears Project Source: GitHub's cached projects, releases and XML.
 */
function project_src_github_clear_cache() {
  cache_clear_all('project_src_github', 'cache', TRUE);
  cache_clear_all('%/drupal/release-history/', 'cache_page', TRUE);
}
